spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wendo_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ##### File Upload Configuration #####
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

##### JWT Configuration #####
application:
  security:
    jwt:
      secret-key: 403E631266556A586E2272357538782F413F4428472B4B6250645367566B5970
      expiration: 2592000000 # 30 day
      refresh-token:
        expiration: 2592000000 # 30 days

##### APP Configuration #####
app:
  base-url: http://localhost:8080
  upload-dir: /home/nerd/uploads

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
    display-request-duration: true
    use-root-path: true
    filter: true
  default-produces-media-type: application/json
  show-actuator: false
  writer-with-default-pretty-printer: true
  override-with-generic-response: false
  group-configs:
    - group: v1
      paths-to-match: /api/**