spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wendo_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 403E631266556A586E2272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 day
      refresh-token:
        expiration: 604800000 # 7 days